meta_product_name: "Lums Digital"
meta_title: "Lums Digital - Learn Digital Marketing"
meta_description: "Learn digital marketing from seasoned experts and take your idea to market"
meta_image: "social_image.png" # should exist in `app/assets/images/`
twitter_account: "@LeWagonLondon"
